### ISSUE TITLE
师傅 JSP免杀是不是有什么问题，生成的免杀JSP访问500，webshell都连不上

### ISSUE THREAD

**Issue by Superhero-zero** [xiaogang000/XG_NTAI#1]
如题

**Comment by xiaogang000** [comment]
有具体报错信息吗，tomcat版本java版本信息之类的

**Comment by Superhero-zero** [comment]
> 有具体报错信息吗，tomcat版本java版本信息之类的
![image](https://github.com/xiaogang000/XG_NTAI/assets/66772820/0439b856-9194-49a7-bab3-6ffeedf18e1a)
![image](https://github.com/xiaogang000/XG_NTAI/assets/66772820/0b51c03a-8127-4061-a1ed-33ac6c58c2ee)
这是我在使用的靶场环境和本地java版本，经测试冰蝎、哥斯拉的原生马都是可以连，但是经过工具免杀后的免杀马访问时500，webshell工具链接不上

**Comment by Superhero-zero** [comment]
![image](https://github.com/xiaogang000/XG_NTAI/assets/66772820/6ad765b6-f18c-4fb3-a51f-8ca0080de7a6)
![image](https://github.com/xiaogang000/XG_NTAI/assets/66772820/1db31e39-4c47-418b-967a-c0a56b98f886)
![image](https://github.com/xiaogang000/XG_NTAI/assets/66772820/214d2b22-98a8-40ed-95f8-214e541397af)

**Comment by xiaogang000** [comment]
jsp_demo1是基于tomcat8和java8写的模板，其他版本tomcat和java还没适配，以后demo会逐步适配版本问题
